# MPI-DPPO with FRESH CRITIC (trained from scratch)
#
# This config trains the critic from scratch during PPO fine-tuning instead of
# loading a pretrained value network checkpoint. This is useful when:
# - You want the critic to adapt to the policy's changing distribution
# - You don't have a pretrained value network
# - You want to compare fresh vs pretrained critic performance
#
# Usage:
#   cd /home/shaoyuan/Documents/Software/motion-policy-improvement
#   poetry run python ../dppo-baseline/script/run.py \
#       --config-path=/home/shaoyuan/Documents/Software/dppo-baseline/cfg/truck_2d \
#       --config-name=ft_ppo_mpi_truck_2d_single_box_fresh_critic
# python script/run.py --config-path=/home/shaoyuan/Documents/Software/dppo-baseline/cfg/truck_2d --config-name=ft_ppo_mpi_truck_2d_single_box_fresh_critic
# python script/run.py --config-path=/teamspace/studios/this_studio/dppo-baseline/cfg/truck_2d --config-name=ft_ppo_mpi_truck_2d_single_box_fresh_critic

defaults:
  - _self_

hydra:
  run:
    dir: ${logdir}
  job_logging:
    loggers:
      matplotlib.axes._base:
        level: ERROR
      agent.finetune.train_ppo_diffusion_truck2d_agent:
        level: INFO

_target_: agent.finetune.train_ppo_diffusion_truck2d_agent.TrainPPODiffusionTruck2DAgent

name: single_box_ddpm_sampling_fix_ft_denoise_50
# logdir: ${oc.env:DPPO_LOG_DIR,outputs}/truck_2d-mpi-fresh/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
logdir: /teamspace/lightning_storage/cloud-experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${name}

wandb:
  entity: contact_placement
  project: truck_2d-dppo
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}

#==============================================================================
# MPI Checkpoint Paths (only policy needed - critic will be trained fresh)
#==============================================================================
base_policy_path: /teamspace/lightning_storage/cloud-experiments/2025-10-28/05-02-10_base_policy_val_networks_5K_4box_multiout16_policy_only_200Ksteps/iterations/0/policy_training/checkpoints/step_160000-val_loss_0.0072-val_ddim_mse_0.3591.ckpt
policy_normalizer_path: /teamspace/lightning_storage/cloud-experiments/2025-10-28/05-02-10_base_policy_val_networks_5K_4box_multiout16_policy_only_200Ksteps/iterations/0/policy_training/normalizer.pt
# base_policy_path: /teamspace/lightning_storage/cloud-experiments/2025-11-20/04-54-56_dagger_beam_search_post_exit_4box_multiout16_point_contact/iterations/14/policy_training/checkpoints/latest.ckpt
# policy_normalizer_path: /teamspace/lightning_storage/cloud-experiments/2025-11-20/04-54-56_dagger_beam_search_post_exit_4box_multiout16_point_contact/iterations/14/policy_training/normalizer.pt
# base_policy_path: /home/shaoyuan/Documents/Software/motion-policy-improvement/outputs/2025-11-20/04-54-56_dagger_beam_search_post_exit_4box_multiout16_point_contact/iterations/14/policy_training/checkpoints/latest.ckpt
# policy_normalizer_path: /home/shaoyuan/Documents/Software/motion-policy-improvement/outputs/2025-11-20/04-54-56_dagger_beam_search_post_exit_4box_multiout16_point_contact/iterations/14/policy_training/normalizer.pt
# NOTE: critic_path and critic_normalizer_path are NOT needed when use_pretrained_critic=false

#==============================================================================
# Core Configuration
#==============================================================================
seed: 42
device: cuda:0
env_name: truck_2d
obs_dim: 6
action_dim: 5
denoising_steps: 100
ft_denoising_steps: 50
cond_steps: 2
img_cond_steps: 2
critic_img_cond_steps: 1
critic_n_obs_steps: 1
horizon_steps: 32
act_steps: 20
use_ddim: false

#==============================================================================
# Environment Configuration
#==============================================================================
env:
  n_envs: 50
  name: ${env_name}
  env_type: truck_2d
  # Success threshold: with step_reward=-0.1 and act_steps=20, worst-case success
  # (on last step) gives episode_best_reward = -1.9/20 = -0.095. Timeout gives -0.1.
  best_reward_threshold_for_success: 0.405
  max_episode_steps: 200
  save_video: false
  save_meshcat: true
  meshcat_save_freq: 1  # Save meshcats every X iterations (like render.freq)
  approx_n_meshcats_saved: 5
  reinit_freq: 1  # Reinitialize environments every N iterations to reclaim leaked memory (0 to disable)
  specific:
    problem_file: /teamspace/studios/this_studio/motion-policy-improvement/datasets/truck_2d/truck_2d_problems_med_147K.pkl
    # problem_file: /home/shaoyuan/Documents/Software/motion-policy-improvement/datasets/truck_2d/truck_2d_problems_med_147K.pkl
    problem_index_range: [0, 145000]
    control_timestep: 0.1
    physics_timestep: 0.002
    init_x: 1.0
    max_boxes: 1
    enable_tracking_failure: false
    enable_penetration_failure: true
    max_penetration_distance: 0.1
    full_trajectory_mode: false
    act_steps: ${act_steps}
    normalize_actions: false 
    reward_config:
      step_reward: -0.1
      failure_reward: -20.0
      success_reward: 10.0
      # Dense reward mode
      dense_reward_enabled: true
      grasp_reward: 1.0
      failed_grasp_penalty: -1.0
      drop_reward: 2.0
      failed_drop_penalty: -2.0
      max_reward_distance: 3.0
      dense_reward_scale: 0.08
  wrappers:
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true

shape_meta:
  obs:
    rgb:
      shape: [1, 71, 192]
    state:
      shape: [6]
    full_state:
      shape: [19]
  action:
    shape: [5]

#==============================================================================
# Training Configuration
# NOTE: n_critic_warmup_itr is important for fresh critic - keeps actor frozen
#       while the randomly-initialized critic learns initial value estimates
#==============================================================================
train:
  n_train_itr: 500
  n_critic_warmup_itr: 2
  n_steps: 180
  gamma: 0.999
  augment: false
  grad_accumulate: 100
  actor_lr: 1e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-5
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-3
  save_model_freq: 10
  val_freq: 10
  render:
    freq: 10
    num: 0
  reward_scale_running: true
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 100
  logprob_batch_size: 200
  update_epochs: 10
  vf_coef: 0.5
  target_kl: 1.0

#==============================================================================
# Model - MPI PPO Diffusion with FRESH CRITIC
#==============================================================================
model:
  _target_: model.diffusion.mpi_ppo_diffusion.MPIPPODiffusion.from_mpi_checkpoints
  
  # Policy checkpoint (required)
  policy_checkpoint_path: ${base_policy_path}
  policy_normalizer_path: ${policy_normalizer_path}
  
  # Fresh critic configuration
  use_pretrained_critic: false  # <-- KEY: Set to false for fresh critic
  critic_type: mpi  # Explicitly set to mpi (default)
  critic:
    # This instantiates a fresh ResNet18-based value network
    _target_: value_network.models.resnet18_tv_truck_2d_value_network.ResNet18TVTruck2dValueNetwork
    img_shape: [1, 71, 192]
    state_dim: 6
    features_dim: 512
    use_tanh: false  # <-- IMPORTANT: Disable Tanh for PPO (need unbounded values)
  
  # Model architecture params
  ft_denoising_steps: ${ft_denoising_steps}
  denoising_steps: ${denoising_steps}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  device: ${device}
  critic_n_obs_steps: ${critic_n_obs_steps}
  critic_img_cond_steps: ${critic_img_cond_steps}
  
  # PPO params
  gamma_denoising: 0.99
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.001
  clip_ploss_coef_rate: 3
  norm_adv: true
  min_sampling_denoising_std: 0.1
  min_logprob_denoising_std: 0.1
  denoised_clip_value: 1.0
  randn_clip_value: 3
