# MPI-DPPO with DPPO's ViTCritic (trained from scratch)
#
# This config uses DPPO's standard ViTCritic instead of MPI's ResNet18 critic.
# The ViTCritic is ~20x smaller (~0.5M vs ~11M params) and proven to work
# for DPPO image-based tasks.
#
# Key differences from MPI critic:
# - Uses VitEncoder backbone (lightweight vision transformer)
# - Images must be converted from [0,1] to [0,255] (handled by DPPOViTCriticWrapper)
# - augment must be false (RandomShiftsAug requires square images)
#
# Usage:
#   cd /home/shaoyuan/Documents/Software/motion-policy-improvement
#   poetry run python ../dppo-baseline/script/run.py \
#       --config-path=/home/shaoyuan/Documents/Software/dppo-baseline/cfg/truck_2d \
#       --config-name=ft_ppo_mpi_truck_2d_vit_critic
# python script/run.py --config-path=/home/shaoyuan/Documents/Software/dppo-baseline/cfg/truck_2d --config-name=ft_ppo_mpi_truck_2d_vit_critic

defaults:
  - _self_

hydra:
  run:
    dir: ${logdir}
  job_logging:
    loggers:
      matplotlib.axes._base:
        level: ERROR
      agent.finetune.train_ppo_diffusion_truck2d_agent:
        level: INFO

_target_: agent.finetune.train_ppo_diffusion_truck2d_agent.TrainPPODiffusionTruck2DAgent

name: truck_2d_dppo_vit_critic
logdir: ${oc.env:DPPO_LOG_DIR,outputs}/truck_2d-vit-critic/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}

wandb:
  entity: contact_placement
  project: truck_2d-dppo
  run: ${now:%H-%M-%S}_${name}

#==============================================================================
# MPI Checkpoint Paths (only policy needed - critic will be trained fresh)
#==============================================================================
base_policy_path: /home/shaoyuan/Documents/Software/motion-policy-improvement/outputs/2025-08-07/20-39-40_train_truck_2d_diffusion_policy_5K_full_truck_point_contact_03-51-35_local/checkpoints/step_035000-val_loss_0.0091-val_ddim_mse_0.1280.ckpt
policy_normalizer_path: /home/shaoyuan/Documents/Software/motion-policy-improvement/outputs/2025-08-07/20-39-40_train_truck_2d_diffusion_policy_5K_full_truck_point_contact_03-51-35_local/normalizer.pt

#==============================================================================
# Core Configuration
#==============================================================================
seed: 42
device: cuda:0
env_name: truck_2d
obs_dim: 6
action_dim: 5
denoising_steps: 100
ft_denoising_steps: 10
cond_steps: 2
img_cond_steps: 2
critic_img_cond_steps: 1  # Critic uses single frame
critic_n_obs_steps: 1     # Critic uses single state observation
horizon_steps: 32
act_steps: 20
use_ddim: false

#==============================================================================
# Environment Configuration
#==============================================================================
env:
  n_envs: 30
  name: ${env_name}
  env_type: truck_2d
  best_reward_threshold_for_success: 0.405
  max_episode_steps: 200
  save_video: false
  save_meshcat: true
  meshcat_save_freq: 2
  approx_n_meshcats_saved: 5
  specific:
    problem_file: "/home/shaoyuan/Documents/Software/motion-policy-improvement/datasets/truck_2d/truck_2d_problems_med_147K.pkl"
    problem_index_range: [0, 145000]
    control_timestep: 0.1
    physics_timestep: 0.002
    init_x: 1.0
    max_boxes: 1
    enable_tracking_failure: false
    enable_penetration_failure: true
    max_penetration_distance: 0.1
    full_trajectory_mode: false
    act_steps: ${act_steps}
    normalize_actions: false 
    reward_config:
      step_reward: -0.1
      failure_reward: -20.0
      success_reward: 10.0
  wrappers:
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true

shape_meta:
  obs:
    rgb:
      shape: [1, 71, 192]
    state:
      shape: [6]
  action:
    shape: [5]

#==============================================================================
# Training Configuration
#==============================================================================
train:
  n_train_itr: 500
  n_critic_warmup_itr: 10
  n_steps: 300
  gamma: 0.999
  augment: false
  grad_accumulate: 20
  actor_lr: 2e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 5
    min_lr: 2e-5
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-3
  save_model_freq: 50
  val_freq: 10
  render:
    freq: 10
    num: 0
  reward_scale_running: true
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 500
  logprob_batch_size: 240
  update_epochs: 10
  vf_coef: 0.5
  target_kl: 1.0

#==============================================================================
# Model - MPI PPO Diffusion with DPPO ViTCritic
#==============================================================================
model:
  _target_: model.diffusion.mpi_ppo_diffusion.MPIPPODiffusion.from_mpi_checkpoints
  
  # Policy checkpoint (required)
  policy_checkpoint_path: ${base_policy_path}
  policy_normalizer_path: ${policy_normalizer_path}
  
  # Fresh ViTCritic configuration
  use_pretrained_critic: false
  critic_type: vit  # <-- Use DPPO's ViTCritic
  critic:
    _target_: model.common.critic.ViTCritic
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      # num_channel = C * img_cond_steps (grayscale * history frames)
      num_channel: ${critic_img_cond_steps}
      img_h: 71
      img_w: 192
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    img_cond_steps: ${critic_img_cond_steps}
    spatial_emb: 128
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: true
    # cond_dim = state_dim * critic_n_obs_steps
    cond_dim: ${eval:'${obs_dim} * ${critic_n_obs_steps}'}
    augment: false  # REQUIRED: Non-square images break RandomShiftsAug
  
  # Model architecture params
  ft_denoising_steps: ${ft_denoising_steps}
  denoising_steps: ${denoising_steps}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  device: ${device}
  critic_n_obs_steps: ${critic_n_obs_steps}
  critic_img_cond_steps: ${critic_img_cond_steps}
  
  # PPO params
  gamma_denoising: 0.99
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.001
  clip_ploss_coef_rate: 3
  norm_adv: true
  min_sampling_denoising_std: 0.1
  min_logprob_denoising_std: 0.1
  denoised_clip_value: 1.0
  randn_clip_value: 3
