# DPPO fine-tuning with MPI pretrained models
#
# Usage:
#   cd /home/shaoyuan/Documents/Software/motion-policy-improvement
#   poetry run python ../dppo-baseline/script/run.py \
#       --config-path=/home/shaoyuan/Documents/Software/dppo-baseline/cfg/truck_2d \
#       --config-name=ft_ppo_mpi_truck_2d

defaults:
  - _self_

hydra:
  run:
    dir: ${logdir}
  job_logging:
    loggers:
      matplotlib.axes._base:
        level: ERROR
      agent.finetune.train_ppo_diffusion_truck2d_agent:
        level: INFO

_target_: agent.finetune.train_ppo_diffusion_truck2d_agent.TrainPPODiffusionTruck2DAgent

name: truck_2d_mpi_ft
logdir: ${oc.env:DPPO_LOG_DIR,outputs}/truck_2d-mpi-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}

#==============================================================================
# MPI Checkpoint Paths
#==============================================================================
base_policy_path: /home/shaoyuan/Documents/Software/motion-policy-improvement/outputs/2025-12-08/20-17-32_base_policy_val_networks_5K_4box_singleout_vit/iterations/0/policy_training/checkpoints/latest.ckpt
critic_path: /home/shaoyuan/Documents/Software/motion-policy-improvement/outputs/2025-12-08/20-17-32_base_policy_val_networks_5K_4box_singleout_vit/iterations/0/value_network_training/checkpoints/latest.pt
policy_normalizer_path: /home/shaoyuan/Documents/Software/motion-policy-improvement/outputs/2025-12-08/20-17-32_base_policy_val_networks_5K_4box_singleout_vit/iterations/0/policy_training/normalizer.pt
critic_normalizer_path: /home/shaoyuan/Documents/Software/motion-policy-improvement/outputs/2025-12-08/20-17-32_base_policy_val_networks_5K_4box_singleout_vit/iterations/0/value_network_training/value_network_normalizer.pt

#==============================================================================
# Core Configuration
#==============================================================================
seed: 42
device: cuda:0
env_name: truck_2d
obs_dim: 6
action_dim: 5
denoising_steps: 100
ft_denoising_steps: 10
cond_steps: 2
img_cond_steps: 2
critic_img_cond_steps: 1
critic_n_obs_steps: 1
horizon_steps: 32
act_steps: 16
use_ddim: false

#==============================================================================
# Environment
#==============================================================================
env:
  n_envs: 8
  name: ${env_name}
  env_type: truck_2d
  best_reward_threshold_for_success: -50.0
  max_episode_steps: 500
  save_video: false
  save_meshcat: true
  approx_n_meshcats_saved: 5
  specific:
    problem_file: "/home/shaoyuan/Documents/Software/motion-policy-improvement/datasets/truck_2d/truck_2d_problems_med_147K.pkl"
    problem_index_range: [0, 10000]
    control_timestep: 0.1
    physics_timestep: 0.002
    init_x: 1.0
    max_boxes: 4
    enable_tracking_failure: false
    enable_penetration_failure: true
    max_penetration_distance: 0.1
    full_trajectory_mode: false
    act_steps: ${act_steps}
    normalize_actions: false
    reward_config:
      step_reward: -0.1
      failure_reward: -80.0
      success_reward: 0.0
  wrappers:
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true

shape_meta:
  obs:
    rgb:
      shape: [1, 71, 192]
    state:
      shape: [6]
  action:
    shape: [5]

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY,contact_placement}
  project: truck_2d-mpi-finetune
  run: ${now:%H-%M-%S}_${name}

#==============================================================================
# Training
#==============================================================================
train:
  n_train_itr: 500
  n_critic_warmup_itr: 5
  n_steps: 100
  gamma: 0.999
  augment: false
  grad_accumulate: 4
  actor_lr: 1e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-6
  critic_lr: 1e-4
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-5
  save_model_freq: 50
  val_freq: 25
  render:
    freq: 50
    num: 0
  reward_scale_running: true
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 64
  logprob_batch_size: 64
  update_epochs: 10
  vf_coef: 0.5
  target_kl: 0.1

#==============================================================================
# Model - MPI PPO Diffusion (loaded from checkpoints)
#==============================================================================
model:
  _target_: model.diffusion.mpi_ppo_diffusion.MPIPPODiffusion.from_mpi_checkpoints
  # Checkpoint paths
  policy_checkpoint_path: ${base_policy_path}
  policy_normalizer_path: ${policy_normalizer_path}
  critic_checkpoint_path: ${critic_path}
  critic_normalizer_path: ${critic_normalizer_path}
  # Model params
  ft_denoising_steps: ${ft_denoising_steps}
  denoising_steps: ${denoising_steps}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  device: ${device}
  # Critic config
  critic_n_obs_steps: ${critic_n_obs_steps}
  critic_img_cond_steps: ${critic_img_cond_steps}
  # PPO params
  gamma_denoising: 0.99
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.001
  clip_ploss_coef_rate: 3
  norm_adv: true
  # Sampling params
  min_sampling_denoising_std: 0.1
  min_logprob_denoising_std: 0.1
  denoised_clip_value: 1.0
  randn_clip_value: 3
