defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.train_ppo_diffusion_img_agent.TrainPPOImgDiffusionAgent

name: truck_2d_ft_diffusion_unet_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/truck_2d-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
# Set these paths based on your setup
base_policy_path: ???  # Path to pretrained policy checkpoint
critic_path: null  # Optional: Path to pretrained critic checkpoint (for warm-starting value function)
normalizer_checkpoint_path: null  # Optional: Path to LinearNormalizer checkpoint from mpi

seed: 42
device: cuda:0
env_name: truck_2d
obs_dim: 6  # 4 joints + suction_cmd + is_suctioned
action_dim: 5  # 4 joints + suction command
denoising_steps: 100
ft_denoising_steps: 10
cond_steps: 2  # Number of observation history steps
img_cond_steps: 2  # Number of image history steps (images are stacked along channels)
horizon_steps: 32  # Action chunk size
act_steps: 20  # Action execution steps
use_ddim: True

env:
  n_envs: 16  # Number of parallel environments
  name: ${env_name}
  env_type: truck_2d
  best_reward_threshold_for_success: -1.0  # Any episode with reward > -1.0 is considered success
  max_episode_steps: 1000  # Maximum steps per episode
  save_video: False
  # Environment-specific kwargs
  problem_file: "datasets/truck_2d/truck_2d_problems_med_147K.pkl"
  problem_index_range: [0, 145000]
  control_timestep: 0.1
  physics_timestep: 0.005
  wrappers:
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

shape_meta:
  obs:
    rgb:
      shape: [1, 71, 192]  # Grayscale depth image
    state:
      shape: [6]  # 4 joints + suction_cmd + is_suctioned
  action:
    shape: [5]  # 4 joints + suction command

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: truck_2d-finetune
  run: ${now:%H-%M-%S}_${name}

train:
  n_train_itr: 200  # Number of training iterations
  n_critic_warmup_itr: 5  # Number of iterations to warm up critic before policy training
  n_steps: 1000  # Steps per environment per iteration
  gamma: 0.999  # Discount factor
  augment: False  # Disable image augmentation (grayscale non-square images)
  grad_accumulate: 8  # Gradient accumulation steps
  actor_lr: 5e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 5e-5
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-3
  save_model_freq: 50
  val_freq: 10
  render:
    freq: 1
    num: 0
  # PPO specific
  reward_scale_running: True
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 256
  logprob_batch_size: 256
  update_epochs: 10
  vf_coef: 0.5
  target_kl: 1

model:
  _target_: model.diffusion.diffusion_ppo.PPODiffusion
  # HP to tune
  gamma_denoising: 0.99
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.001
  clip_ploss_coef_rate: 3
  randn_clip_value: 3
  min_sampling_denoising_std: 0.1
  min_logprob_denoising_std: 0.1
  #
  use_ddim: ${use_ddim}
  ddim_steps: ${ft_denoising_steps}
  learn_eta: False
  eta:
    base_eta: 1
    input_dim: ${obs_dim}
    mlp_dims: [256, 256]
    action_dim: ${action_dim}
    min_eta: 0.1
    max_eta: 1.0
    _target_: model.diffusion.eta.EtaFixed
  network_path: ${base_policy_path}
  critic_path: ${critic_path}  # For loading pretrained critic
  actor:
    _target_: model.diffusion.unet.VisionUnet1D
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'1 * ${img_cond_steps}'}  # Grayscale: 1 channel per timestep
      img_h: ${shape_meta.obs.rgb.shape[1]}
      img_w: ${shape_meta.obs.rgb.shape[2]}
      cfg:
        patch_size: 8
        depth: 2
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    img_cond_steps: ${img_cond_steps}
    augment: False  # Disabled for grayscale non-square images
    spatial_emb: 128
    diffusion_step_embed_dim: 32
    dim: 40
    dim_mults: [1, 2]
    kernel_size: 5
    n_groups: 8
    smaller_encoder: False
    cond_predict_scale: True
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
  critic:
    _target_: model.common.critic.ViTCritic
    spatial_emb: 128
    augment: False  # Disabled for grayscale non-square images
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'1 * ${img_cond_steps}'}  # Grayscale: 1 channel per timestep
      img_h: ${shape_meta.obs.rgb.shape[1]}
      img_w: ${shape_meta.obs.rgb.shape[2]}
      cfg:
        patch_size: 8
        depth: 2
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    img_cond_steps: ${img_cond_steps}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
  ft_denoising_steps: ${ft_denoising_steps}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}
